name: Onboard AWS Project

on:
  workflow_call:
    secrets:
      TFE_TOKEN:
        required: true
      TF_VCS_OAUTH_TOKEN_ID:
        required: true
      GITHUB_PAT:
        required: true

jobs:
  onboard:
    uses: subhamay-bhattacharyya-gha/aws-project-onboarding/.github/workflows/aws-project-onboarding.yaml@feature/GHA-0003-feat-make-link-vcs-step-o
    secrets: inherit
